spring:
  application:
    name: storage-service
  mvc:
    servlet:
      path: /storage-service # // localhost:8080/storage-service/storage-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
#server:
#  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: project


server:
  port: 8011
